
name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd swift-market && npm install

      - name: Build project
        run: cd swift-market && npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          action: deploy
          project_id: 'swift-market-2363d'
          service_account: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          firebase_tools_version: latest
          target: hosting
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
